### ISSUE TITLE
html-live CircleCI job does not work anymore after jupyter-book update

### ISSUE THREAD

**Issue by joergbrech** [joergbrech/Modellbildung-und-Simulation#78]
Invoking

https://github.com/joergbrech/Modellbildung-und-Simulation/blob/b4110094cd1c261b20454284b13b8fcbfac526ed/.circleci/config.yml#L90

manually works, but it fails in the `html-live` job of circleci with this error message:

```
#!/bin/bash -eo pipefail
ghp-import -m "[skip ci] Update Site" -p -n -f _build/html

fatal: unable to fork
Traceback (most recent call last):
  File "/usr/local/bin/ghp-import", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/ghp_import.py", line 242, in main
    git.check_call('push', opts.remote, opts.branch, '--force')
  File "/usr/local/lib/python3.6/dist-packages/ghp_import.py", line 106, in check_call
    sp.check_call(['git'] + list(args), **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'push', 'origin', 'gh-pages', '--force']' returned non-zero exit status 128.

Exited with code exit status 1
CircleCI received exit code 1
```

Until this is fixed, we need to update the gh-pages branch manually after each merge into master :cry:

**Comment by joergbrech** [comment]
Fixed! There was something wrong with the mtmiller/octave docker image. Maybe git could not be found? Who knows...works with circleci/python:3.6-stretch
